receivers:
  otlp:
    protocols:
      grpc:
processors:
  attributes:
    actions:
      - action: insert
        key: "X-SampleRatio"
        value: 0.5

exporters:
  otlp:
    endpoint: tempo:4417
    tls:
      insecure: true
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [attributes]
      exporters: [otlp]
