version: "3.9"

networks:
  default:
    name: poc
    driver: bridge

services:
  hello-world:
    build: hello-world
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4317
      - OTEL_SERVICE_NAME=hello-world
      - FOO_ENDPOINT=http://foo:8081
    depends_on:
      otelcol:
        condition: service_started
    restart: unless-stopped
  foo:
    build: foo
    ports:
      - "8081:8081"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4317
      - OTEL_SERVICE_NAME=foo
    depends_on:
      otelcol:
        condition: service_started
    restart: unless-stopped
  otelcol:
    image: otel/opentelemetry-collector-contrib:0.87.0
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"     # OTLP over gRPC receiver
      - "4318:4318"     # OTLP over HTTP receiver
    restart: unless-stopped
  k6:
    platform: linux/amd64
    image: grafana/k6
    volumes:
      - ../config/k6-script.js:/k6-script.js
    command:
      - run
      - /k6-script.js
    depends_on:
      - hello-world
