extensions:
  health_check: {}
  basicauth/grafana_cloud_tempo:
    client_auth:
      username: "182484"
      password: "glc_eyJvIjoiNjE5NzIzIiwibiI6InN0YWNrLTMzNjg1Ni1pbnRlZ3JhdGlvbi1pcmluYS1vdGVsLWRlbW8taXJpbmEtb3RlbC1kZW1vIiwiayI6IjVoMGx5VEc2dnpiMjIzcHQ3VDFLUDlTNyIsIm0iOnsiciI6ImV1In19"
  basicauth/grafana_cloud_prometheus:
    client_auth:
      username: "374002"
      password: "glc_eyJvIjoiNjE5NzIzIiwibiI6InN0YWNrLTMzNjg1Ni1pbnRlZ3JhdGlvbi1pcmluYS1vdGVsLWRlbW8taXJpbmEtb3RlbC1kZW1vIiwiayI6IjVoMGx5VEc2dnpiMjIzcHQ3VDFLUDlTNyIsIm0iOnsiciI6ImV1In19"
  basicauth/grafana_cloud_loki:
    client_auth:
      username: "185971"
      password: "glc_eyJvIjoiNjE5NzIzIiwibiI6InN0YWNrLTMzNjg1Ni1pbnRlZ3JhdGlvbi1pcmluYS1vdGVsLWRlbW8taXJpbmEtb3RlbC1kZW1vIiwiayI6IjVoMGx5VEc2dnpiMjIzcHQ3VDFLUDlTNyIsIm0iOnsiciI6ImV1In19"
receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
  batch:
exporters:
  debug:
  otlp/grafana_cloud_traces:
    endpoint: "tempo-eu-west-0.grafana.net:443"
    auth:
      authenticator: basicauth/grafana_cloud_tempo
  loki/grafana_cloud_logs:
    endpoint: "https://logs-prod-eu-west-0.grafana.net/loki/api/v1/push"
    auth:
      authenticator: basicauth/grafana_cloud_loki
  prometheusremotewrite/grafana_cloud_metrics:
    endpoint: "https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push"
    auth:
      authenticator: basicauth/grafana_cloud_prometheus
service:
  extensions: [health_check, basicauth/grafana_cloud_tempo, basicauth/grafana_cloud_prometheus, basicauth/grafana_cloud_loki]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/grafana_cloud_traces]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite/grafana_cloud_metrics]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, loki/grafana_cloud_logs]
